version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:22.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-hash-{{ checksum "yarn.lock" }}
            - deps-hash- # used if checksum fails

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: deps-hash-{{ checksum "yarn.lock" }}

      - run: yarn build
      # does not work on circle ci because memory runs out
      # - run:
      #     name: "Integration Tests"
      #     command: yarn test-integration
