version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-hash-{{ checksum "yarn.lock" }}
            - deps-hash- # used if checksum fails

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: deps-hash-{{ checksum "yarn.lock" }}

      - run:
          name: "Unit Tests with Coverage"
          command: |
            mkdir -p ./reports/junit/
            yarn test:ci --config=jest.config.js
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
            JEST_JUNIT_OUTPUT_NAME: test-results.xml

      - store_test_results:
          path: ./reports/junit/

      - run:
          name: "Upload Coverage to Codecov"
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN} -f ./coverage/coverage-final.json

      - store_artifacts:
          path: ./coverage
          destination: coverage

      - run:
          name: "Build"
          command: yarn build
      # does not work on circle ci because memory runs out
      # - run:
      #     name: "Integration Tests"
      #     command: yarn test-integration
