version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.11.1-browsers
    resource_class: large
    steps:
      - checkout

      # Install Chrome (latest stable)
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - restore_cache:
          keys:
            - deps-hash-{{ checksum "yarn.lock" }}
            - deps-hash- # used if checksum fails

      - run:
          name: Install Dependencies
          command: |
            yarn install
            yarn cypress verify

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/Cypress
          key: deps-hash-{{ checksum "yarn.lock" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Start Server
          command: yarn start
          background: true

      - run:
          name: Wait for Server
          command: |
            timeout=30
            counter=0
            until curl --output /dev/null --silent --head --fail http://localhost:3000; do
              if [ $counter -eq $timeout ]; then
                echo "Timed out waiting for server to start"
                exit 1
              fi
              counter=$((counter+1))
              echo "Waiting for server to start... ($counter/$timeout)"
              sleep 1
            done

      - run:
          name: Run Cypress Tests
          command: |
            yarn cypress run --browser chrome --headless
          no_output_timeout: 30m

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
